=== oracle/macaron/tests/repo_finder/resources/find_source_report_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "macaron-json-report-schema",
    "title": "Macaron JSON Report",
    "$comment": "For any details about the schema specification and validation documentation, see https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-00 and https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-00.",
    "type": "object",
    "properties": {
        "purl": {
            "type": "string"
        },
        "commit": {
            "type": "string"
        },
        "repo": {
            "type": "string"
        },
        "repo_validated": {
            "type": "boolean"
        },
        "commit_validated": {
            "type": "boolean"
        },
        "url": {
            "type": "string"
        }
    }
}

=== oracle/macaron/tests/integration/cases/golang_googleapis_go-genproto/expected.source.json
{
    "purl": "pkg:golang/google.golang.org/genproto@v0.0.0-20251124214823-79d6a2a4884",
    "commit": "79d6a2a4884",
    "repo": "https://github.com/googleapis/go-genproto",
    "repo_validated": false,
    "commit_validated": false,
    "url": "https://github.com/googleapis/go-genproto/commit/79d6a2a4884"
}

=== oracle/macaron/tests/integration/cases/maven_acra_unusual_tag/acra-core.source.json
{
    "purl": "pkg:maven/ch.acra/acra-core@5.12.0\u00c3",
    "commit": "8d52a1df9fec10b8f2dd95793a3873b49778e011",
    "repo": "https://github.com/ACRA/acra",
    "repo_validated": false,
    "commit_validated": false,
    "url": "https://github.com/ACRA/acra/commit/8d52a1df9fec10b8f2dd95793a3873b49778e011"
}
